"use client";

import type { Metadata } from "next";
import "./globals.css";
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth";
import SessionProvider from "@/hocs/session-provider";
import { useSession } from "next-auth/react";
// export const metadata: Metadata = {
//   title: "Room App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="w-full">
          <SessionProvider>
            {children}
          </SessionProvider>
        </div>
      </body>
    </html>
  );
}

const Loading = ({ children }: { children: React.ReactNode }) => {
  const { data } = useSession();
  if (data) return children;
  return (
    <div className=" w-screen h-screen bg-slate-100 flex items-center justify-center">
      <div className="lds-roller">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  );
};
