import type { Metadata } from 'next'
import './globals.css'
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth";
import SessionProvider from '@/hocs/session-provider'

export const metadata: Metadata = {
  title: 'Room App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='hehe'>
        <SessionProvider>{children}</SessionProvider>
        </div>
     
        </body>
    </html>
  )
}
